title: Codebook for df2
subtitle: dataset of the average mean and std of each included variable by each subject and activity. The df2 dataset was created from the UCI HAR Dataset accessible here: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones. 

# Data report overview
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 
't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a 
corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and 
tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the 
magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, 
tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, 
fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals, which were included in this dataset are: 

mean(): Mean value
std(): Standard deviation

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

These variables were observed in 30 subjects who each performed 6 different activities. The observations of each variable were averaged for each subject and 
activity


For more information about this dataset contact: activityrecognition@smartlab.ws

License:
========
Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.


The dataset examined has the following dimensions:

---------------------------------
Feature                    Result
------------------------ --------
Number of observations        180

Number of variables            75
---------------------------------

# Codebook summary table

---------------------------------------------------------------------------------------------------
Label   Variable                                     Class         # unique  Missing  Description  
                                                                     values                        
------- -------------------------------------------- ----------- ---------- --------- -------------
        **[subject]**                                integer             30  0.00 %   Observations of 30 subjects            

        **[activity]**                               character            6  0.00 %   Activities performed by each subject during which observations were made.
        
        **[tBodyAcc.mean...X]**                      numeric            180  0.00 %                

        **[tBodyAcc.mean...Y]**                      numeric            180  0.00 %                

        **[tBodyAcc.mean...Z]**                      numeric            180  0.00 %                

        **[tGravityAcc.mean...X]**                   numeric            180  0.00 %                

        **[tGravityAcc.mean...Y]**                   numeric            180  0.00 %                

        **[tGravityAcc.mean...Z]**                   numeric            180  0.00 %                

        **[tBodyAccJerk.mean...X]**                  numeric            180  0.00 %                

        **[tBodyAccJerk.mean...Y]**                  numeric            180  0.00 %                

        **[tBodyAccJerk.mean...Z]**                  numeric            180  0.00 %                

        **[tBodyGyro.mean...X]**                     numeric            180  0.00 %                

        **[tBodyGyro.mean...Y]**                     numeric            180  0.00 %                

        **[tBodyGyro.mean...Z]**                     numeric            180  0.00 %                

        **[tBodyGyroJerk.mean...X]**                 numeric            180  0.00 %                

        **[tBodyGyroJerk.mean...Y]**                 numeric            180  0.00 %                

        **[tBodyGyroJerk.mean...Z]**                 numeric            180  0.00 %                

        **[tBodyAccMag.mean..]**                     numeric            180  0.00 %                

        **[tGravityAccMag.mean..]**                  numeric            180  0.00 %                

        **[tBodyAccJerkMag.mean..]**                 numeric            180  0.00 %                

        **[tBodyGyroMag.mean..]**                    numeric            180  0.00 %                

        **[tBodyGyroJerkMag.mean..]**                numeric            180  0.00 %                

        **[fBodyAcc.mean...X]**                      numeric            180  0.00 %                

        **[fBodyAcc.mean...Y]**                      numeric            180  0.00 %                

        **[fBodyAcc.mean...Z]**                      numeric            180  0.00 %                

        **[fBodyAccJerk.mean...X]**                  numeric            180  0.00 %                

        **[fBodyAccJerk.mean...Y]**                  numeric            180  0.00 %                

        **[fBodyAccJerk.mean...Z]**                  numeric            180  0.00 %                

        **[fBodyGyro.mean...X]**                     numeric            180  0.00 %                

        **[fBodyGyro.mean...Y]**                     numeric            180  0.00 %                

        **[fBodyGyro.mean...Z]**                     numeric            180  0.00 %                

        **[fBodyAccMag.mean..]**                     numeric            180  0.00 %                

        **[fBodyBodyAccJerkMag.mean..]**             numeric            180  0.00 %                

        **[fBodyBodyGyroMag.mean..]**                numeric            180  0.00 %                

        **[fBodyBodyGyroJerkMag.mean..]**            numeric            180  0.00 %                

        **[angle.tBodyAccMean.gravity.]**            numeric            180  0.00 %                

        **[angle.tBodyAccJerkMean..gravityMean.]**   numeric            180  0.00 %                

        **[angle.tBodyGyroMean.gravityMean.]**       numeric            180  0.00 %                

        **[angle.tBodyGyroJerkMean.gravityMean.]**   numeric            180  0.00 %                

        **[angle.X.gravityMean.]**                   numeric            180  0.00 %                

        **[angle.Y.gravityMean.]**                   numeric            180  0.00 %                

        **[angle.Z.gravityMean.]**                   numeric            180  0.00 %                

        **[tBodyAcc.std...X]**                       numeric            180  0.00 %                

        **[tBodyAcc.std...Y]**                       numeric            180  0.00 %                

        **[tBodyAcc.std...Z]**                       numeric            180  0.00 %                

        **[tGravityAcc.std...X]**                    numeric            180  0.00 %                

        **[tGravityAcc.std...Y]**                    numeric            180  0.00 %                

        **[tGravityAcc.std...Z]**                    numeric            180  0.00 %                

        **[tBodyAccJerk.std...X]**                   numeric            180  0.00 %                

        **[tBodyAccJerk.std...Y]**                   numeric            180  0.00 %                

        **[tBodyAccJerk.std...Z]**                   numeric            180  0.00 %                

        **[tBodyGyro.std...X]**                      numeric            180  0.00 %                

        **[tBodyGyro.std...Y]**                      numeric            180  0.00 %                

        **[tBodyGyro.std...Z]**                      numeric            180  0.00 %                

        **[tBodyGyroJerk.std...X]**                  numeric            180  0.00 %                

        **[tBodyGyroJerk.std...Y]**                  numeric            180  0.00 %                

        **[tBodyGyroJerk.std...Z]**                  numeric            180  0.00 %                

        **[tBodyAccMag.std..]**                      numeric            180  0.00 %                

        **[tGravityAccMag.std..]**                   numeric            180  0.00 %                

        **[tBodyAccJerkMag.std..]**                  numeric            180  0.00 %                

        **[tBodyGyroMag.std..]**                     numeric            180  0.00 %                

        **[tBodyGyroJerkMag.std..]**                 numeric            180  0.00 %                

        **[fBodyAcc.std...X]**                       numeric            180  0.00 %                

        **[fBodyAcc.std...Y]**                       numeric            180  0.00 %                

        **[fBodyAcc.std...Z]**                       numeric            180  0.00 %                

        **[fBodyAccJerk.std...X]**                   numeric            180  0.00 %                

        **[fBodyAccJerk.std...Y]**                   numeric            180  0.00 %                

        **[fBodyAccJerk.std...Z]**                   numeric            180  0.00 %                

        **[fBodyGyro.std...X]**                      numeric            180  0.00 %                

        **[fBodyGyro.std...Y]**                      numeric            180  0.00 %                

        **[fBodyGyro.std...Z]**                      numeric            180  0.00 %                

        **[fBodyAccMag.std..]**                      numeric            180  0.00 %                

        **[fBodyBodyAccJerkMag.std..]**              numeric            180  0.00 %                

        **[fBodyBodyGyroMag.std..]**                 numeric            180  0.00 %                

        **[fBodyBodyGyroJerkMag.std..]**             numeric            180  0.00 %                
---------------------------------------------------------------------------------------------------




# Variable list
## subject


-----------------------------------
Feature                      Result
------------------------- ---------
Variable type               integer

Number of missing obs.      0 (0 %)

Number of unique values          30

Median                         15.5

1st and 3rd quartiles         8; 23

Min. and max.                 1; 30
-----------------------------------




\fullline

## activity


-------------------------------------
Feature                        Result
------------------------- -----------
Variable type               character

Number of missing obs.        0 (0 %)

Number of unique values             6

Mode                         "laying"
-------------------------------------




\fullline

## tBodyAcc.mean...X


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values            180

Median                            0.28

1st and 3rd quartiles       0.27; 0.28

Min. and max.                0.22; 0.3
--------------------------------------




\fullline

## tBodyAcc.mean...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.02

1st and 3rd quartiles       -0.02; -0.01

Min. and max.                   -0.04; 0
----------------------------------------




\fullline

## tBodyAcc.mean...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.11

1st and 3rd quartiles        -0.11; -0.1

Min. and max.               -0.15; -0.08
----------------------------------------




\fullline

## tGravityAcc.mean...X


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.92

1st and 3rd quartiles        0.84; 0.94

Min. and max.               -0.68; 0.97
---------------------------------------




\fullline

## tGravityAcc.mean...Y


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                            -0.13

1st and 3rd quartiles       -0.23; 0.09

Min. and max.               -0.48; 0.96
---------------------------------------




\fullline

## tGravityAcc.mean...Z


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.02

1st and 3rd quartiles       -0.12; 0.15

Min. and max.                -0.5; 0.96
---------------------------------------




\fullline

## tBodyAccJerk.mean...X


--------------------------------------
Feature                         Result
------------------------- ------------
Variable type                  numeric

Number of missing obs.         0 (0 %)

Number of unique values            180

Median                            0.08

1st and 3rd quartiles       0.07; 0.08

Min. and max.               0.04; 0.13
--------------------------------------




\fullline

## tBodyAccJerk.mean...Y


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.01

1st and 3rd quartiles           0; 0.01

Min. and max.               -0.04; 0.06
---------------------------------------




\fullline

## tBodyAccJerk.mean...Z


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                                0

1st and 3rd quartiles          -0.01; 0

Min. and max.               -0.07; 0.04
---------------------------------------




\fullline

## tBodyGyro.mean...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.03

1st and 3rd quartiles       -0.05; -0.02

Min. and max.                -0.21; 0.19
----------------------------------------




\fullline

## tBodyGyro.mean...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.07

1st and 3rd quartiles       -0.09; -0.06

Min. and max.                 -0.2; 0.03
----------------------------------------




\fullline

## tBodyGyro.mean...Z


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.09

1st and 3rd quartiles         0.07; 0.1

Min. and max.               -0.07; 0.18
---------------------------------------




\fullline

## tBodyGyroJerk.mean...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.1

1st and 3rd quartiles        -0.1; -0.09

Min. and max.               -0.16; -0.02
----------------------------------------




\fullline

## tBodyGyroJerk.mean...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.04

1st and 3rd quartiles       -0.05; -0.04

Min. and max.               -0.08; -0.01
----------------------------------------




\fullline

## tBodyGyroJerk.mean...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.05

1st and 3rd quartiles       -0.06; -0.05

Min. and max.               -0.09; -0.01
----------------------------------------




\fullline

## tBodyAccMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.48

1st and 3rd quartiles       -0.96; -0.09

Min. and max.                -0.99; 0.64
----------------------------------------




\fullline

## tGravityAccMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.48

1st and 3rd quartiles       -0.96; -0.09

Min. and max.                -0.99; 0.64
----------------------------------------




\fullline

## tBodyAccJerkMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.82

1st and 3rd quartiles       -0.98; -0.25

Min. and max.                -0.99; 0.43
----------------------------------------




\fullline

## tBodyGyroMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.66

1st and 3rd quartiles       -0.95; -0.22

Min. and max.                -0.98; 0.42
----------------------------------------




\fullline

## tBodyGyroJerkMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.86

1st and 3rd quartiles       -0.99; -0.51

Min. and max.                   -1; 0.09
----------------------------------------




\fullline

## fBodyAcc.mean...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.77

1st and 3rd quartiles       -0.98; -0.22

Min. and max.                   -1; 0.54
----------------------------------------




\fullline

## fBodyAcc.mean...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.59

1st and 3rd quartiles       -0.95; -0.06

Min. and max.                -0.99; 0.52
----------------------------------------




\fullline

## fBodyAcc.mean...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.72

1st and 3rd quartiles       -0.96; -0.32

Min. and max.                -0.99; 0.28
----------------------------------------




\fullline

## fBodyAccJerk.mean...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.81

1st and 3rd quartiles       -0.98; -0.28

Min. and max.                -0.99; 0.47
----------------------------------------




\fullline

## fBodyAccJerk.mean...Y


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                            -0.78

1st and 3rd quartiles       -0.97; -0.2

Min. and max.               -0.99; 0.28
---------------------------------------




\fullline

## fBodyAccJerk.mean...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.87

1st and 3rd quartiles       -0.98; -0.47

Min. and max.                -0.99; 0.16
----------------------------------------




\fullline

## fBodyGyro.mean...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.73

1st and 3rd quartiles       -0.97; -0.34

Min. and max.                -0.99; 0.47
----------------------------------------




\fullline

## fBodyGyro.mean...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.81

1st and 3rd quartiles       -0.97; -0.45

Min. and max.                -0.99; 0.33
----------------------------------------




\fullline

## fBodyGyro.mean...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.79

1st and 3rd quartiles       -0.96; -0.26

Min. and max.                -0.99; 0.49
----------------------------------------




\fullline

## fBodyAccMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.67

1st and 3rd quartiles       -0.96; -0.16

Min. and max.                -0.99; 0.59
----------------------------------------




\fullline

## fBodyBodyAccJerkMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.79

1st and 3rd quartiles       -0.98; -0.19

Min. and max.                -0.99; 0.54
----------------------------------------




\fullline

## fBodyBodyGyroMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.77

1st and 3rd quartiles       -0.96; -0.41

Min. and max.                 -0.99; 0.2
----------------------------------------




\fullline

## fBodyBodyGyroJerkMag.mean..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.88

1st and 3rd quartiles       -0.98; -0.58

Min. and max.                   -1; 0.15
----------------------------------------




\fullline

## angle.tBodyAccMean.gravity.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.01

1st and 3rd quartiles       -0.01; 0.02

Min. and max.               -0.16; 0.13
---------------------------------------




\fullline

## angle.tBodyAccJerkMean..gravityMean.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                                0

1st and 3rd quartiles       -0.02; 0.02

Min. and max.                -0.12; 0.2
---------------------------------------




\fullline

## angle.tBodyGyroMean.gravityMean.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.02

1st and 3rd quartiles       -0.02; 0.06

Min. and max.               -0.39; 0.44
---------------------------------------




\fullline

## angle.tBodyGyroJerkMean.gravityMean.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                            -0.02

1st and 3rd quartiles       -0.06; 0.03

Min. and max.               -0.22; 0.18
---------------------------------------




\fullline

## angle.X.gravityMean.


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.74

1st and 3rd quartiles       -0.79; -0.58

Min. and max.                -0.95; 0.74
----------------------------------------




\fullline

## angle.Y.gravityMean.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.17

1st and 3rd quartiles        0.02; 0.24

Min. and max.               -0.87; 0.42
---------------------------------------




\fullline

## angle.Z.gravityMean.


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                             0.01

1st and 3rd quartiles       -0.08; 0.11

Min. and max.               -0.87; 0.39
---------------------------------------




\fullline

## tBodyAcc.std...X


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                            -0.75

1st and 3rd quartiles       -0.98; -0.2

Min. and max.                  -1; 0.63
---------------------------------------




\fullline

## tBodyAcc.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.51

1st and 3rd quartiles       -0.94; -0.03

Min. and max.                -0.99; 0.62
----------------------------------------




\fullline

## tBodyAcc.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.65

1st and 3rd quartiles       -0.95; -0.23

Min. and max.                -0.99; 0.61
----------------------------------------




\fullline

## tGravityAcc.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.97

1st and 3rd quartiles       -0.98; -0.95

Min. and max.                  -1; -0.83
----------------------------------------




\fullline

## tGravityAcc.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.96

1st and 3rd quartiles       -0.97; -0.94

Min. and max.               -0.99; -0.64
----------------------------------------




\fullline

## tGravityAcc.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.95

1st and 3rd quartiles       -0.96; -0.92

Min. and max.               -0.99; -0.61
----------------------------------------




\fullline

## tBodyAccJerk.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.81

1st and 3rd quartiles       -0.98; -0.22

Min. and max.                -0.99; 0.54
----------------------------------------




\fullline

## tBodyAccJerk.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.78

1st and 3rd quartiles       -0.97; -0.15

Min. and max.                -0.99; 0.36
----------------------------------------




\fullline

## tBodyAccJerk.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.88

1st and 3rd quartiles       -0.98; -0.51

Min. and max.                -0.99; 0.03
----------------------------------------




\fullline

## tBodyGyro.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.79

1st and 3rd quartiles       -0.97; -0.44

Min. and max.                -0.99; 0.27
----------------------------------------




\fullline

## tBodyGyro.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.8

1st and 3rd quartiles       -0.96; -0.42

Min. and max.                -0.99; 0.48
----------------------------------------




\fullline

## tBodyGyro.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.8

1st and 3rd quartiles       -0.96; -0.31

Min. and max.                -0.99; 0.56
----------------------------------------




\fullline

## tBodyGyroJerk.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.84

1st and 3rd quartiles       -0.98; -0.46

Min. and max.                   -1; 0.18
----------------------------------------




\fullline

## tBodyGyroJerk.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.89

1st and 3rd quartiles       -0.98; -0.59

Min. and max.                    -1; 0.3
----------------------------------------




\fullline

## tBodyGyroJerk.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.86

1st and 3rd quartiles       -0.98; -0.47

Min. and max.                   -1; 0.19
----------------------------------------




\fullline

## tBodyAccMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.61

1st and 3rd quartiles       -0.94; -0.21

Min. and max.                -0.99; 0.43
----------------------------------------




\fullline

## tGravityAccMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.61

1st and 3rd quartiles       -0.94; -0.21

Min. and max.                -0.99; 0.43
----------------------------------------




\fullline

## tBodyAccJerkMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.8

1st and 3rd quartiles       -0.98; -0.22

Min. and max.                -0.99; 0.45
----------------------------------------




\fullline

## tBodyGyroMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.74

1st and 3rd quartiles       -0.95; -0.36

Min. and max.                 -0.98; 0.3
----------------------------------------




\fullline

## tBodyGyroJerkMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.88

1st and 3rd quartiles       -0.98; -0.58

Min. and max.                   -1; 0.25
----------------------------------------




\fullline

## fBodyAcc.std...X


---------------------------------------
Feature                          Result
------------------------- -------------
Variable type                   numeric

Number of missing obs.          0 (0 %)

Number of unique values             180

Median                            -0.75

1st and 3rd quartiles       -0.98; -0.2

Min. and max.                  -1; 0.66
---------------------------------------




\fullline

## fBodyAcc.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.51

1st and 3rd quartiles       -0.94; -0.08

Min. and max.                -0.99; 0.56
----------------------------------------




\fullline

## fBodyAcc.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.64

1st and 3rd quartiles       -0.95; -0.27

Min. and max.                -0.99; 0.69
----------------------------------------




\fullline

## fBodyAccJerk.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.83

1st and 3rd quartiles       -0.98; -0.25

Min. and max.                   -1; 0.48
----------------------------------------




\fullline

## fBodyAccJerk.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.79

1st and 3rd quartiles       -0.97; -0.17

Min. and max.                -0.99; 0.35
----------------------------------------




\fullline

## fBodyAccJerk.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.9

1st and 3rd quartiles       -0.98; -0.54

Min. and max.               -0.99; -0.01
----------------------------------------




\fullline

## fBodyGyro.std...X


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.81

1st and 3rd quartiles       -0.98; -0.48

Min. and max.                 -0.99; 0.2
----------------------------------------




\fullline

## fBodyGyro.std...Y


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                              -0.8

1st and 3rd quartiles       -0.96; -0.42

Min. and max.                -0.99; 0.65
----------------------------------------




\fullline

## fBodyGyro.std...Z


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.82

1st and 3rd quartiles       -0.96; -0.39

Min. and max.                -0.99; 0.52
----------------------------------------




\fullline

## fBodyAccMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.65

1st and 3rd quartiles       -0.95; -0.37

Min. and max.                -0.99; 0.18
----------------------------------------




\fullline

## fBodyBodyAccJerkMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.81

1st and 3rd quartiles       -0.98; -0.27

Min. and max.                -0.99; 0.32
----------------------------------------




\fullline

## fBodyBodyGyroMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.77

1st and 3rd quartiles       -0.95; -0.43

Min. and max.                -0.98; 0.24
----------------------------------------




\fullline

## fBodyBodyGyroJerkMag.std..


----------------------------------------
Feature                           Result
------------------------- --------------
Variable type                    numeric

Number of missing obs.           0 (0 %)

Number of unique values              180

Median                             -0.89

1st and 3rd quartiles       -0.98; -0.61

Min. and max.                   -1; 0.29
----------------------------------------


For more information about this dataset contact: activityrecognition@smartlab.ws

License:
========
Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.


